const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const lab=require('../../static/dashboard_simulation_lab.js');
const near=(actual,expected,tolerance=.01)=>assert(Math.abs(actual-expected)<tolerance,`${actual} != ${expected}`);
let model=new lab.LabModel();
model.preset('approach');
let target=model.selected(),a=lab.assess(target,model.site);
assert.equal(a.status,'outside');assert.equal(a.trend,'approaching');near(a.zoneEta,14);near(a.arrivalEta,19.2);
model.step(14);assert.equal(model.alerts.length,1);assert.equal(lab.assess(target,model.site).status,'inside');
model.acknowledge(model.alerts[0].id);model.step(1);assert.equal(model.alerts.length,0,'same entry does not repeatedly alert');
model.positionTarget(target.id,{x:300,y:0});model.positionTarget(target.id,{x:20,y:0});assert.equal(model.alerts.length,1,'re-entry starts a new episode');
model.loseTarget(target.id);assert.equal(lab.assess(target,model.site).status,'lost');assert.equal(lab.assess(target,model.site).arrivalEta,null);assert.equal(model.alerts.length,0);
model.leave();assert.equal(model.playing,false);assert.equal(model.alerts.length,0);

const systemAlarm=new lab.LabModel();systemAlarm.setSite({x:0,y:0},20);systemAlarm.addNode({x:-200,y:0});systemAlarm.addNode({x:100,y:0});systemAlarm.setAllNodeDetectionRadius(500);
const truthInside=systemAlarm.createEvent({kind:'drone',position:{x:0,y:0},speed:0});assert.equal(lab.assess(truthInside,systemAlarm.site).status,'inside');assert.equal(lab.assessSystem(truthInside,systemAlarm.site).status,'outside');assert.equal(systemAlarm.alerts.length,0,'truth path alone cannot trigger a system warning');
systemAlarm.positionTarget(truthInside.id,{x:80,y:0});assert.equal(lab.assess(truthInside,systemAlarm.site).status,'outside');assert.equal(lab.assessSystem(truthInside,systemAlarm.site).status,'inside');assert.equal(systemAlarm.alerts.length,1,'the warning follows the estimated system path even while truth is outside');

model.preset('one');assert.equal(model.nodes[0].detectionRadius,450);assert.equal(model.reportingNodes().length,1);assert.equal(model.sourceRegion().kind,'circle');assert.equal(model.selected().estimatedPosition,null,'one detection cannot estimate a route');
model.preset('two');assert.equal(model.reportingNodes().length,2);assert.equal(model.geometry().length,2);assert.equal(model.sourceRegion().kind,'line');near(model.selected().estimatedPosition.x,0);near(model.selected().estimatedPosition.y,-120);
model.positionTarget(model.selectedId,{x:40,y:-100});model.replayEvent(model.events[0].id);assert(model.replay.estimatedPoints.length>=2,'history owns a snapshot of the estimated path');model.replay=null;model.positionTarget(model.selectedId,{x:0,y:-120});
assert.equal(model.setAllNodeDetectionRadius(100),true);assert(model.nodes.every(n=>n.detectionRadius===100),'one control updates every node range');assert.equal(model.reportingNodes().length,0,'nodes outside the shared radius are excluded');assert.equal(model.selected().estimatedPosition,null);
assert.equal(model.setAllNodeDetectionRadius(10),false);assert.equal(model.setAllNodeDetectionRadius(5001),false);
model.setAllNodeDetectionRadius(450);assert.equal(model.addNode({x:0,y:0}).detectionRadius,450,'new nodes inherit the shared range');model.nodes.pop();model.nodes[0].online=false;model.refreshEstimates(true);assert.equal(model.geometry().length,1);model.nodes[0].online=true;model.nodes[0].reporting=false;model.refreshEstimates(true);assert.equal(model.reportingNodes().length,1,'disabled nodes do not participate');
model.preset('three');assert.equal(model.reportingNodes().length,3);assert.equal(model.geometry().length,3);assert.equal(model.sourceRegion().kind,'polygon');assert(model.selected().estimatedPosition);const positions=model.nodes.map(n=>({x:n.x,y:n.y}));model.step(1);assert.deepEqual(model.nodes.map(n=>({x:n.x,y:n.y})),positions,'fixed nodes remain stable during motion');
assert.deepEqual([1,2,3,4,5].map(n=>lab.nodeVisual(n).shape),['circle','square','triangle','diamond','hexagon'],'simulation nodes follow the V2.2 shape sequence');
assert.equal(lab.nodeVisual(1,true,false).fill,'#F8FAFC');assert.equal(lab.nodeVisual(2,true,true,0).scale,14);assert.equal(lab.nodeVisual(2,true,true,1).scale,20);assert.equal(lab.nodeVisual(2,true,true).fill,'#F97316');
const stableOrdinal=model.nodes[1].ordinal;model.nodes.shift();assert.equal(model.nodes[0].ordinal,stableOrdinal,'deleting another node does not change this node shape');
assert.equal(lab.hull([{x:0,y:0},{x:1,y:0},{x:2,y:0}]).length,2,'collinear nodes do not create a fictitious polygon');
assert.equal(lab.hull([{x:0,y:0},{x:0,y:0},{x:2,y:0}]).length,2,'coincident nodes are deduplicated');
model.preset('missing');assert.equal(model.selected().position,null);assert.equal(model.selected().trail.length,0);assert.equal(model.alerts.length,0);assert.equal(lab.assess(model.selected(),model.site).zoneEta,null);
model.replayEvent(model.events[0].id);assert.equal(model.replay.playing,false);assert.equal(lab.replayPoint(model.replay),null);
model.preset('non_drone');model.positionTarget(model.selectedId,{x:0,y:0});assert.equal(model.alerts.length,0,'non-drone events never trigger drone geofence alarms');
model.preset('passby');assert.equal(lab.assess(model.selected(),model.site).arrivalEta,null);assert.equal(lab.assess(model.selected(),model.site).zoneEta,null);
model.preset('depart');assert.equal(lab.assess(model.selected(),model.site).trend,'departing');assert.equal(lab.assess(model.selected(),model.site).zoneEta,null);
model.preset('multiple');assert.equal(model.targets.length,2);assert.equal(model.selectedId,model.alerts[0].targetId);
model.createEvent({position:{x:-500,y:0},speed:10,heading:90});assert.equal(model.selectedId,model.alerts[0].targetId,'new outside events do not steal pending warning focus');
model.preset('idle');assert.equal(model.targets.length,0);assert.equal(model.nodes.length,3);assert.equal(model.playing,false);

model=new lab.LabModel();model.addNode({x:1,y:2});target=model.createEvent({position:{x:0,y:0},speed:10,heading:90});
target.waypoints=[{x:10,y:0},{x:10,y:10}];model.step(1.5);near(target.position.x,10);near(target.position.y,5);model.step(1);near(target.position.y,10);assert.equal(target.speed,0,'stops at final path waypoint');
model.replayEvent(model.events[0].id);const saved=JSON.stringify(model.replay.points);target.trail.push({x:200,y:200,time:50});assert.equal(JSON.stringify(model.replay.points),saved,'replay owns a stable snapshot');
assert.equal(model.playing,false);assert(model.replay.playing);model.replay.fraction=.5;assert(lab.replayPoint(model.replay));model.leave();assert.equal(model.replay.playing,false);
const sharedReplay={points:[{x:0,y:0,time:0},{x:100,y:0,time:10}],fraction:.25};const trueAtQuarter=lab.replayPoint(sharedReplay);assert.equal(trueAtQuarter.time,2.5);assert.equal(lab.replayPointAtTime([{x:20,y:0,time:5},{x:40,y:0,time:10}],trueAtQuarter.time),null,'estimate waits for its real timestamp instead of starting early');
const estimateAtSharedTime=lab.replayPointAtTime([{x:20,y:0,time:5},{x:40,y:0,time:10}],7.5);near(estimateAtSharedTime.x,30);
assert.equal(model.setSite({x:0,y:0},-2),false);assert.equal(model.setSite({x:0,y:0},6000),false);assert.equal(model.addNode({x:Infinity,y:0}),null);
assert.equal(model.moveNode(model.nodes[0].id,{x:22,y:31}),true);assert.equal(model.nodes[0].x,22);
model=new lab.LabModel();const fleet=[model.createEvent({kind:'drone',position:{x:-100,y:0},speed:12,heading:90}),model.createEvent({kind:'drone',position:{x:0,y:100},speed:8,heading:180}),model.createEvent({kind:'drone',position:{x:100,y:0},speed:5,heading:270})];assert.equal(fleet.length,3);assert.equal(new Set(fleet.map(t=>`${t.position.x},${t.position.y}`)).size,3,'users can add drones one by one at separate positions');assert.equal(model.playing,false,'adding one or more drones does not start playback');model.step(1);assert(fleet.every((t,i)=>t.trail.length===2),'one playback clock advances every configured drone');
model.addNode({x:0,y:0});model.events[0].points=undefined;model.clearTargets();assert.equal(model.targets.length,0);assert.equal(model.nodes.length,1);assert.equal(model.events.length,3);assert.equal(model.replayEvent(model.events[0].id),true);assert(model.replay.points.length,'clearing active targets preserves independent history playback');model.clearHistory();assert.equal(model.events.length,0);assert.equal(model.replay,null);model.clearNodes();assert.equal(model.nodes.length,0);
const clearNodesModel=new lab.LabModel();clearNodesModel.addNode({x:-100,y:0});clearNodesModel.addNode({x:100,y:0});const sensed=clearNodesModel.createEvent({kind:'drone',position:{x:0,y:0},speed:0});assert(sensed.estimatedTrail.length);clearNodesModel.clearNodes();assert.equal(sensed.estimatedTrail.length,0,'clearing nodes removes their live estimate');clearNodesModel.replayEvent(clearNodesModel.events[0].id);assert(clearNodesModel.replay.estimatedPoints.length,'clearing nodes preserves the independent history snapshot');
model.reset();for(let i=0;i<125;i++)model.addNode({x:i,y:i});assert.equal(model.nodes.length,lab.LIMITS.nodes);
for(let i=0;i<100;i++)model.createEvent({position:null});assert.equal(model.targets.length,lab.LIMITS.targets);
const p={x:150,y:-800};const restored=lab.offset(lab.latLng(p));near(restored.x,p.x);near(restored.y,p.y);

const isolated=new lab.LabModel();assert.equal(isolated.targets.length,0,'separate model instances never share state');
const source=fs.readFileSync(path.join(__dirname,'../../static/dashboard_simulation_lab.js'),'utf8');
assert(!/\bfetch\s*\(|\bWebSocket\s*\(|\bXMLHttpRequest\b|\blocalStorage\b|\bsessionStorage\b|\bEventSource\s*\(/.test(source),'simulation performs no API, socket, or shared persistence operations');
assert(!/root\.(?:state|map|broadcast|renderDashboard|loadDashboard)/.test(source),'simulation does not modify real dashboard globals');
assert(source.includes('this.googleOverlays=new Map()'),'Google overlays use stable keyed objects');
assert(!/renderGoogle\(\)\s*\{[^}]*this\.clearGoogle\(\)/s.test(source),'animation does not delete every Google overlay on each frame');
assert(!source.includes('data-field="unlocated"')&&!source.includes('data-action="place-target"'),'redundant pre-create location and sound-only controls are removed');
assert(source.includes('<details class="slab-node-list">')&&!source.includes('<details class="slab-node-list" open>'),'long placed-node lists are independently collapsed by default');
console.log('simulation lab: sensor ranges, estimated path, isolated state, alerts, ETA, movement and dual-path replay passed');
