const assert=require('node:assert/strict');
const {analyze,availability,MAX_SECONDS}=require('../../static/dashboard_audio_evidence.js');
const rate=16000;
const tone=(hz,seconds=1,amplitude=.5)=>Float32Array.from({length:Math.round(rate*seconds)},(_,i)=>amplitude*Math.sin(2*Math.PI*hz*i/rate));
const peak=frame=>frame.indexOf(Math.max(...frame));
const result=analyze(tone(1000),rate);
assert.equal(result.duration,1);
assert.equal(peak(result.spectrum[0])*rate/result.fftSize,1000);
assert(Math.abs(result.spectrum[0][64]-20*Math.log10(.5))<.05,'tone amplitude has known dBFS');
assert(result.waveform.some(([min,max])=>min<-.49 && max>.49));
const silence=analyze(new Float32Array(rate),rate);
assert(silence.spectrum.every(frame=>frame.every(value=>value===-80)),'silence must not invent spectral energy');
assert(silence.waveform.every(([min,max])=>min===0 && max===0));
const changing=new Float32Array(rate*2); changing.set(tone(1000)); changing.set(tone(3000),rate);
const sweep=analyze(changing,rate);
assert.equal(peak(sweep.spectrum[0])*rate/sweep.fftSize,1000);
assert.equal(peak(sweep.spectrum.at(-1))*rate/sweep.fftSize,3000);
assert.throws(()=>analyze(new Float32Array(rate*(MAX_SECONDS+1)),rate),/audio_too_long/);
assert.throws(()=>analyze(new Float32Array([NaN]),rate),/audio_invalid/);
assert.throws(()=>analyze(new Float32Array(0),rate),/audio_invalid/);
assert.equal(analyze(new Float32Array([0]),rate).spectrum.length,1);
assert.equal(availability({audio_path:'a.wav'},{gcs_configured:false}).available,false);
assert.equal(availability({audio_path:'a.wav'},{}).available,false);
assert.equal(availability({audio_path:'a.wav'},{gcs_configured:true}).available,true);
assert.match(availability({audio_encoding_status:'failed'}).text,/編碼失敗/);
console.log('Audio analysis: tone frequency, dBFS amplitude, silence, time order and bounds passed');
